[features]
seeds = false
skip-lint = false

[programs.localnet]
oracle_escrow = "YOUR_PROGRAM_ID_PLACEHOLDER"

[programs.devnet]
oracle_escrow = "YOUR_PROGRAM_ID_PLACEHOLDER"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/blitz-dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
